spring.application.name=ProjectPulseBackend

spring.datasource.url=jdbc:mysql://localhost:3306/project_pulse?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=GusY.12.8.05.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true